### ISSUE TITLE
the problem of MCMC ?

### ISSUE THREAD

**Issue by bojone** [ritheshkumar95/energy_based_generative_models#4]
you use MCMC on random variable z, which means you think the energy function of z is E(G(z)), where E(x) is the energy function of x and G(z) is generator. But why?

We have p_{\theta}(x) = e^{-E(x)}/Z is a energy distribution of x. If we transform it with x=G(z), we get p(z)=e^{-E(G(z))}/Z * abs(det(dG/dz)), where dG/dz is Jacobian of G. The result is not equal e^{-E(G(z))}/Z.

**Comment by ritheshkumar95** [comment]
As for your first question:
1.) We did it because MCMC in visible space has many issues:
i.) Poor mixing
ii.) Attraction to spurious modes
We tried MCMC is visible MCMC but as mentioned in the paper it didn't work very well.

As for your second observation:
You are absolutely right. In fact, this is the major discussion we had with the reviewers for ICLR 2019.
https://openreview.net/forum?id=HJlmhs05tm
Let me know if those discussions clarify things for you.  In short, yes we don't have theoretical guarantees that we're sampling from the "correct" energy function.
